// Main pages index - organized by modules
export * from './dashboard'
export * from './returns'
export * from './premiums'
export * from './surveillance'
export * from './risk'
export * from './scv'
export * from './reports'
export * from './administration'

// Individual page exports for direct imports
export { default as LoginPage } from './LoginPage'
export { default as Dashboard } from './dashboard/Dashboard'
export { default as ReturnsInbox } from './returns/ReturnsInbox'
export { default as ValidationLogs } from './returns/ValidationLogs'
export { default as ReturnRepository } from './returns/ReturnRepository'
export { default as PenaltiesEnforcement } from './returns/PenaltiesEnforcement'
export { default as PremiumCalculation } from './premiums/PremiumCalculation'
export { default as InvoiceManagement } from './premiums/InvoiceManagement'
export { default as PaymentReconciliation } from './premiums/PaymentReconciliation'
export { default as PenaltyManagement } from './premiums/PenaltyManagement'
export { default as DepositTrends } from './surveillance/DepositTrends'
export { default as ExposureAnalysis } from './surveillance/ExposureAnalysis'
export { default as CamelsPerformance } from './surveillance/CamelsPerformance'
export { default as InstitutionComparison } from './surveillance/InstitutionComparison'
export { default as RiskScoring } from './risk/RiskScoring'
export { default as PredictiveAnalytics } from './risk/PredictiveAnalytics'
export { default as AnomalyDetection } from './risk/AnomalyDetection'
export { default as StressTesting } from './risk/StressTesting'
export { default as ComplianceTracker } from './risk/ComplianceTracker'
export { default as SCVSummary } from './scv/SCVSummary'
export { default as DepositRegister } from './scv/DepositRegister'
export { default as SCVSimulation } from './scv/SCVSimulation'
export { default as ReportBuilder } from './reports/ReportBuilder'
export { default as TrendsKPIs } from './reports/TrendsKPIs'
export { default as ExportTools } from './reports/ExportTools'
export { default as UserRoleManagement } from './administration/UserRoleManagement'
export { default as SystemSettings } from './administration/SystemSettings'
export { default as AuditTrail } from './administration/AuditTrail'
export { default as IntegrationSettings } from './administration/IntegrationSettings'
